### ISSUE TITLE
Bug: Volume Import fails

### ISSUE THREAD

**Issue by S3bb1** [andrewbaxter/terraform-provider-fly#7]
When trying to import a volume we get the following error

`Error: AttributeName("internalid") still remains in the path: could not find attribute or block "internalid" in schema` 

maybe this is a leftover, but shouldnt this line https://github.com/andrewbaxter/terraform-provider-fly/blob/main/provider/volumeResource.go#L237

be just `id` then? because the `Read` method uses just id and not internalId. Previously the provider used `internalId` to fetch the volumes.

**Comment by S3bb1** [comment]
Ping @andrewbaxter. Would be cool if we can get this merged

**Comment by andrewbaxter** [comment]
Oh sorry, for some reason my notifications aren't working entirely on this repo.  Thanks for the ping!
